name: git-sync

on: 
  - push
  - delete

jobs:
  sync_macos:
    runs-on: ubuntu-latest
    name: Git Sync MacOS
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: aramirol/git-sync@v0.1
      with:
        gitlab-url: ${{ secrets.GITLAB_URL }}
        gitlab-username: ${{ secrets.GITLAB_USERNAME }}
        gitlab-token: ${{ secrets.GITLAB_TOKEN }}
